# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-cloud-spanner
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  title: terraform-google-cloud-spanner
  source:
    repo: https://github.com/anaik91/terraform-google-cloud-spanner.git
    sourceType: git
  actuationTool:
    type: Terraform
    version: '>= 0.13'
  examples:
  - name: simple_example
    location: examples/simple_example
  variables:
  - name: backup_schedule
    description: The Backup Schedule in CRON format
    type: string
    required: true
  - name: backup_schedule_region
    description: The schedule to be enabled on scheduler to trigger spanner DB backup
    type: string
    default: us-central1
    required: false
  - name: project_id
    description: The project ID to deploy to
    type: string
    required: true
  - name: workflow_argument
    description: The arguments to workflow as JSON encoded
    type: string
    required: true
  roles:
  - level: Project
    roles:
    - roles/owner
  services:
  - iam.googleapis.com
  - cloudresourcemanager.googleapis.com
  - storage-api.googleapis.com
  - serviceusage.googleapis.com
  - workflows.googleapis.com
  - cloudscheduler.googleapis.com
  - spanner.googleapis.com
  - pubsub.googleapis.com
  - logging.googleapis.com
  - storage.googleapis.com
